### ISSUE TITLE
Request for Data Format Example

### ISSUE THREAD

**Issue by swampx** [XAIseries/LEXNet#1]
I would greatly appreciate it if you could provide a sample of the data format or a brief description of it. This information will be immensely helpful for me in a project I am currently working on.

**Comment by XAIseries** [comment]
Hello, 

Thank you for your message.

The format of the input data is the following: tabular data with 
-	First dimension: each row represents a sample/a flow
-	Second dimension: each column represents a packet (value: +/- packet size)

Best,
