### ISSUE TITLE
data

### ISSUE THREAD

**Issue by 1Opera** [XAIseries/LEXNet#2]
您好，我对您的实验很感兴趣，想复现您的实验，不知道可否提供数据集？我的邮箱是zmx@e.gzhu.edu.cn。

**Comment by light-zealous** [comment]
Hello, I am very interested in your experiment and would like to replicate your experiment. Could you please provide me with the data set? My email address is pieceless01@gmail.com

**Comment by XAIseries** [comment]
Hello,

An anonymized version of the dataset is available [here.](https://figshare.com/articles/dataset/AppClassNet_-_A_commercial-grade_dataset_for_application_identification_research/20375580)

Best,
